### ISSUE TITLE
Long-term statistics

### ISSUE THREAD

**Issue by deb0ro** [oyvindwe/connectlife-ha#5]
Hi, great integration, working like a charm after update to 0.0.6 :)

One thing I noticed now is that integration cannot be used to display nice graphs using long-term statistics, the dropdown entries are missing values for connectlife completely. Can you take a look at https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics as suggested in the UI when you have time? :)

Thank you and good work!

**Comment by oyvindwe** [comment]
That is a good point; I was actually missing history myself. It's a bit tricky to set the correct state class without proper data dictionaries for the various device types though.

I think we need to figure out a good way to define data dictionaries based on observed values, where state class is one of the properties.

**Comment by oyvindwe** [comment]
This should be fixed in version 0.2.0

**Comment by deb0ro** [comment]
Hi, its now working as expected for all reading I tried except one, "sensor.refrigerator_freeze_real_temperature" - that is still not having long-term statics :/ Is there something I can try to debug this? Thanks.

**Comment by deb0ro** [comment]
"Refrigerator freeze real temperature" is not even listed there, for example "Refrigerator refrigerator real temperature" is there.

**Comment by oyvindwe** [comment]
You get a value in the UI?
Have you checked the log file?

**Comment by deb0ro** [comment]
Yes, I get the value in the UI - just not the long-term graphs like for the rest.

I can see this error:
```
Logger: custom_components.connectlife.dictionaries
Source: custom_components/connectlife/dictionaries.py:216
integration: ConnectLife ([documentation](https://github.com/oyvindwe/connectlife-ha))
First occurred: 1:39:47 PM (1 occurrences)
Last logged: 1:39:47 PM
```

No data dictionary found for Refrigerator (026-1b0610z0049j)

**Comment by oyvindwe** [comment]
Yes, that warning is expected until a data dictionary is added for the device.

I found the bug - it breaks for negative numbers. All values are returned as strings in the ConnectLife API), and the check for integers is wrong in the upstream library: https://github.com/oyvindwe/connectlife/blob/v0.2.0/connectlife/appliance.py#L56

Will fix later today.

**Comment by oyvindwe** [comment]
[Version 0.7.2](https://github.com/oyvindwe/connectlife-ha/releases/tag/v0.7.2) that should fix this issue is released!

I don't have any sensors with negative numbers, so please verify!

**Comment by oyvindwe** [comment]
Thanks for verifying!

Do you want to try to make a data dictionary for your fridge? Or you can provide a JSON dump, and I'll can give it a try.

**Comment by deb0ro** [comment]
What do you mean by "data dictionary"? But I can provide you with the dump as well, just let me know how to obtain it :)

**Comment by oyvindwe** [comment]
[Data dictionaries](https://github.com/oyvindwe/connectlife-ha/tree/main/custom_components/connectlife/data_dictionaries) map ConnectLife API properties to Home Assistant to it is possible to create switches and select menus, set unit, icon, and provide translations strings.

Instruction on how to make a JSON dump is here: https://github.com/oyvindwe/connectlife

**Comment by deb0ro** [comment]
[hisenserefrigeratordump.json](https://github.com/user-attachments/files/16168153/hisenserefrigeratordump.json)

Dump attached :)
